/* eslint-disable prettier/prettier */
export const AppActions = {
  ADD_FLOOR: "ADD_FLOOR",
  REMOVE_FLOOR: "REMOVE_FLOOR",
  CLEAR_FULL: "CLEAR_FULL",
  ADD_APARTMENT_TO_FLOOR: "ADD_APARTMENT_TO_FLOOR",
  ADD_ROOM_TO_APARTMENT: "ADD_ROOM_TO_APARTMENT",
  ADD_STRUCTURE_TO_ROOM: "ADD_STRUCTURE_TO_ROOM",
  REMOVE_STRUCTURE_FROM_ROOM: "REMOVE_STRUCTURE_FROM_ROOM",
  EDIT_STRUCTURE_IN_ROOM: "EDIT_STRUCTURE_IN_ROOM",
};
